name: mustache
version: 1.0.0+1
author: Greg Lowe <greg@vis.net.nz>
description: Mustache template library
homepage: https://github.com/xxgreg/mustache

environment:
  sdk: '>=2.0.0-dev.1.2 <2.0.0'  

dev_dependencies:
  build_test: ^0.10.2
  test: any
